services:
  fusional:
    image: fusional
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn core.main:app --host 0.0.0.0 --port 8009"]
    ports:
      - 8009:8009
      - 5678:5678
